name = baunilha
title = Baunilha
author = Mirtilo
supported_games = minetest_game
description = Baunilha is a texture pack that aims to create a refreshed look for Minetest Game. The goal is to create an aesthetic that is cohesive, vibrant and fun to build and explore, while maintaining a vanilla feel.

release = 37613
