title = MINE BUILD
name = MINE BUILD
description = THE base game for APK mine build
author = drred
release = 2
first_mod = 
last_mod = 
disallowed_mapgens = v6,v5,fractal,
default_mapgen = v7
disallowed_mapgen_settings = mgv5_spflags, seed
map_gen_limit = 7500
map_persistent = true
disabled_settings = enable_server
textdomain = mine_build
disallow_singleplayer = false
aliases = build_mine, mine_build
creative_mode = false
enable_damage = true
server_announce = false
allowed_mapgens = v7, flat, singlenode,valleys